### PR TITLE
Pinning Vue.js version as the latest 3.2 does not work

### PR DESCRIPTION
**Pull request by gbel**
Pinning Vue.js version as the latest 3.2 does not work

### CODE REVIEW

**Comment by stephenhensley** [comment]
@gbel thanks for the quick fix!

The actual vue docs and github reflect that the most recent release is still in 2.x so I wonder how unpkg got so far ahead.

I think we should use the recommended link mentioned in the vue docs (probably should have been using this prior as well):

```
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
```

Also, re. your changes to the `run.sh` script: in order to simulate the real URL of the site when running on github pages, it's expected that the `run.sh` command will be run outside of the directory as:

```
./Programmer/run.sh
```

**Comment by gbel** [comment]
@stephenhensley Sorry about the changes on the `run.sh` script I reverted them :)

**Comment by stephenhensley** [comment]
No problem! Just figured I'd mention it, would you mind updating the link to the `cdn.jsdelivr` one mentioned up above as well.

And thanks again for spotting the issue, and jumping on it so quickly!

**Comment by gbel** [comment]
You are welcome! I just got a new module and desperately needed to flash it :) figure out I could land a hand and share the fix!

**Comment by stephenhensley** [comment]
Looks good. Thanks again!

**Pull request merged**
